a=str(input("Introduceti un cuvant:"))
b=str(input("Introduceti un cuvant:"))
c=str(input("Introduceti un cuvant:"))
d=str(input("Introduceti un cuvant:"))
print(a)
print(b)
print(c)
print(d)
print(a+" "+b+" "+c+" "+d+".")