s1=str(input(Introduceti cuvantul:))
s2=str(input(Introduceti cuvantul:))
s3=str(input(Introduceti cuvantul:))
s4=str(input(Introduceti cuvantul:))
print(s1)
print(s2)
print(s3)
print(s4)
print(s1[0:2]+s2[0]+s3[0:3]+s4[])